### ISSUE TITLE
Doxygen not going through C++ files

### ISSUE THREAD

**Issue by Napolitain** [DenverCoder1/C-Workshop#17]
Hi, I checked my Doxyfile, and it works, with an output to docs/html.

I use this into my existing github action
```
    - name: Doxygen GitHub Pages Deploy Action
      uses: DenverCoder1/doxygen-github-pages-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
after my tests pass.

What is possibly problematic? Token? I haven't set any as I saw somewhere it should be automatic. Is it true?

Also my branch gh-pages looks like this :
![image](https://user-images.githubusercontent.com/18146363/148264244-ee2e3120-4bc9-4209-9130-9d125f740558.png)

Thanks!
